repository_type: pipeline

nf_core_version: 3.5.1

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-denver_logo_light.png
    - assets/nf-core-oamd-bio-denver_logo_light.png
    - docs/images/nf-core-denver_logo_light.png
    - docs/images/nf-core-oamd-bio-denver_logo_light.png
    - docs/images/nf-core-denver_logo_dark.png
    - docs/images/nf-core-oamd-bio-denver_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - assets/email_template.html
    - assets/sendmail_template.txt
    - docs/README.md
    - .github/workflows/linting.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-denver_logo_light.png
    - assets/nf-core-oamd-bio-denver_logo_light.png
    - docs/images/nf-core-denver_logo_light.png
    - docs/images/nf-core-oamd-bio-denver_logo_light.png
    - docs/images/nf-core-denver_logo_dark.png
    - docs/images/nf-core-oamd-bio-denver_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/clean-up.yml
    - .github/workflows/download_pipeline.yml
    - .github/workflows/fix_linting.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/template-version-comment.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
  actions_nf_test: false

template:
  org: ph-core
  name: denver
  description: nf-core style NextFlow pipeline for Dengue virus (DENV) analysis
  author: James Smagala
  version: 1.0.0-dev
  force: true
  outdir: denver
  is_nfcore: false
